generatorName: python-fastapi
outputDir: samples/openapi3/server/petstore/python-fastapi
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-object-as-parameter.yaml
templateDir: modules/openapi-generator/src/main/resources/python-fastapi
